// <auto-generated />
using CentroRescateAnimales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroRescateAnimales.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250321045840_datos")]
    partial class datos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroRescateAnimales.Models.Adoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adoptantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan.perez@example.com",
                            Nombre = "Juan Pérez",
                            Telefono = "555-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.gomez@example.com",
                            Nombre = "María Gómez",
                            Telefono = "555-987-6543"
                        });
                });

            modelBuilder.Entity("CentroRescateAnimales.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdoptanteId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdoptanteId");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("CentroRescateAnimales.Models.Animal", b =>
                {
                    b.HasOne("CentroRescateAnimales.Models.Adoptante", "Adoptante")
                        .WithMany("Animales")
                        .HasForeignKey("AdoptanteId");

                    b.Navigation("Adoptante");
                });

            modelBuilder.Entity("CentroRescateAnimales.Models.Adoptante", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
